ALTER TABLE cards ADD COLUMN interval INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN ease_factor REAL NOT NULL DEFAULT 2.5;
ALTER TABLE cards ADD COLUMN repetitions INTEGER NOT NULL DEFAULT 0;
ALTER TABLE cards ADD COLUMN next_review_at TEXT DEFAULT NULL;
